server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yymusic_website?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 825392X
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.music.yymusic_website.domain
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    com.music.yymusic_website.dao: debug

